# Generated by Django 6.0.2 on 2026-02-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processed_by_agent',
            field=models.BooleanField(default=False),
        ),
    ]
